package featureSelection.basic.support.reductMiningStrategy.heuristic;

import featureSelection.basic.support.reductMiningStrategy.ReductMiningStrategy;

public interface HeuristicReductMiningStrategy extends ReductMiningStrategy {}